/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Mar 16 13:47:07 2019. */

#include "simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, frequency, frequency, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SimpleMessage, duty_cycle, frequency, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
