/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Mar 19 10:23:01 2019. */

#include "simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, on_time, on_time, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SimpleMessage, off_time, on_time, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
